### ISSUE TITLE
Document system requirements 

### ISSUE THREAD

**Issue by 0xABAB** [snowplow/iglu#136]
It would be useful to write down how much system resources are required to run iglu. 

I.e. amount of RAM/CPU required for various environments (test, staging, production). I can imagine that the mere serving of the files is really cheap, but there is no lower bound specified, which should really be the minimum amount of technical documentation.

**Comment by alexanderdean** [comment]
Good thinking - let's document. The system requirements will depend largely on the following:

1. Variety of schemas fetched
2. Number of clients
3. Lifespan of clients

Notes:

* We say *variety* of schemas fetched because the clients cache aggressively
* Because clients cache aggressively, client lifespan is very important: 1 short-lived client (e.g. running in AWS Lambda or a PHP webpage) will hit the server far more than 10 long-lived clients (e.g. a Hadoop cluster running once a day)

**Comment by chuwy** [comment]
Wontfix.
