### ISSUE TITLE
Scala Core: add schema matching for unversioned instances

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#148]
See https://github.com/snowplow/iglu/issues/147

We want to find the _highest matching schema version_ for an unversioned instance, where:
- _matching_ means that the instance passes validation against the given schema version
- _highest_ means that no schema versions with higher numbers pass

**Comment by alexanderdean** [comment]
I think @fblundun has some ideas on a performant algorithm here - Fred could you share?

**Comment by alexanderdean** [comment]
@chuwy - should this ticket move to Iglu Scala Client?

**Comment by alexanderdean** [comment]
Migrated https://github.com/snowplow/iglu-scala-client/issues/53

**Comment by chuwy** [comment]
I actually think it should belong to core. But It also depends on *when* do we need it. I don't have plans to migrate iglu client to core in near version. It can introduce breaking changes in SCE, so decided to be very careful on it.

**Comment by alexanderdean** [comment]
Okay, will keep both open for now!

**Comment by fblundun** [comment]
My original idea was to do a binary search for the last matching schema, instead of just checking starting at the most recent schema and working backwards. However I now don't think this is a good idea, because it assumes that for any two schemas A and B such that A is matching and B is not, A is higher than B. This is not necessarily true - in general I think it is only true given the additional assumption that A and B have the same model and revision.

I suppose we could use that information to reduce the number of schemas we check - e.g. if 1-0-9 isn't matching, we know that 1-0-8 and below also aren't matching. So for each model-revision pair, we need only check the latest addition.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/iglu-scala-core/issues/28
