### ISSUE TITLE
Schema DDL: recursive algorithm to determine complex objects and arrays length

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#187]
Migrated from https://github.com/snowplow/schema-ddl/issues/53

**Comment by ninjabear** [comment]
I don't think you need an intelligent algorithm here, setting it to `VARCHAR(max)` (where max is whatever the upper limit of the type is) would do the trick. In fact you could set any you don't know the length of to that, it won't use any more space because of how `VARCHAR` is stored. 

Although having just written that, I saw [this](http://docs.aws.amazon.com/redshift/latest/dg/c_best-practices-smallest-column-size.html), so I may be incorrect!

**Comment by chuwy** [comment]
Hey, thanks @ninjabear. By "intelligent" here I meant "anything better than stupidly use 5000 for any array". Probably I had to use word "recursive".

**Comment by ninjabear** [comment]
Oh! ok fair enough

**Comment by kasper-agg** [comment]
Could it be possible to let _igluctl_ honor `--varchar-size` for generating the `VARCHAR` definition?

**Comment by chuwy** [comment]
Pushing back because of confusion with assignment.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/41
