### ISSUE TITLE
igluctl: warn user if an optional field doesn't allow NULL values

### ISSUE THREAD

**Issue by bogaert** [snowplow/iglu#231]
This is one of the most common bad rows: an event fails validation because an optional field in the schema is sent with a null value, but the schema doesn't allow null. From where I stand, both scenarios are equivalent: not sending the optional field or sending it with a null value.

I propose adding a strong warning when a user wants to create a schema with optional fields that don't allow null. Thoughts?

**Comment by chuwy** [comment]
I like the idea. `null` adds explicitness. #232 proposes way to implement it.

**Comment by alexanderdean** [comment]
I like this.

I think there's another related pattern - which is that an author creates a schema and sets some of the fields to `["<<type>>", "null"]`, implying that the author wants the other fields to be `NOT NULL`, **but** because the author doesn't specify the `required` array, Iglu has to treat all of the fields as tolerating `NULL` - which is unlikely to be the author's intent. This happened to me yesterday. Thoughts?

**Comment by bogaert** [comment]
That's another good one!

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/42

**Comment by edmundadjei** [comment]
This check does not allow me to say that an optional field must not be null if specified, it should simply not be specified. Thoughts? Is there a way around this?
