### ISSUE TITLE
Scala Core: add json4s to test scope

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#236]
Pure `iglu-core` brings unnecessary json4s dependency.

**Comment by chuwy** [comment]
Also for `iglu-core-json4s` we should downgrade json4s to `3.2.11` as it is version we're using everywhere.

**Comment by oguzhanunlu** [comment]
@chuwy since this issue is opened and last updated on Feb 23, I could make use of an update here.

It seems that json4s is being used [here](https://github.com/snowplow/iglu/blob/master/0-common/scala-core/project/IgluCoreBuild.scala#L34) and [here](https://github.com/snowplow/iglu/blob/master/0-common/scala-core/project/IgluCoreBuild.scala#L44). By the way, shouldn't first one be [`json4sTest`](https://github.com/snowplow/iglu/blob/master/0-common/scala-core/project/Dependencies.scala#L33)?

Regarding using downgraded `json4s` in `iglu-core-json4s` , #268 is open to do this. Should we close this issue?

**Comment by chuwy** [comment]
Hey @oguzhanunlu on your first link json4s included as a dependency, but not used in core project itself, so you're exactly right about `json4sTest`, this is whole point of this ticket. In other words - right now if we include `iglu-core`, without json4s we still bring `json4s` transitively.

**Comment by oguzhanunlu** [comment]
Thanks @chuwy , on it.
