### ISSUE TITLE
Schema DDL: add default value for JSON property if default provided

### ISSUE THREAD

**Issue by chuwy** [snowplow/iglu#248]
Migrated from https://github.com/snowplow/schema-guru/issues/106

**Comment by miike** [comment]
@chuwy I might pick this one up over the break if I've got time as I think it'd be a useful addition.

My interpretation of this is to:

1) Being parsing the `default` property in JSON schemas if available
2) Set the DEFAULT argument in the generated Redshift DDL so that it picks it up for any shredded loads.

This does raise the question for databases that don't have an equivalent of DEFAULT built in (e.g., BigQuery) what should be the expected behaviour for the end user? Should this potentially happen in the enrichment process (if value is null replace it with DEFAULT value from schema)?

**Comment by chuwy** [comment]
Hey @miike! Yes, your understanding is correct. And that's a good question regarding other DBs - I think right now most straightforward approach would be just to rollback to non-required/`NULL` types for DB without `DEFAULT`. Maybe later this can be implemented as part of loader part.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/schema-ddl/issues/26
