### ISSUE TITLE
igluctl: fix acronyms handling

### ISSUE THREAD

**Issue by ihortom** [snowplow/iglu#265]
If acronyms are used in event names the CamelCase rule isn't working consistently. While the table name is generated correctly the corresponding jsonpaths/SQL filename is not, which results in "missing jsonpaths" error at data load. I would expect the same algorithm to be used in both cases.

Example (mistreatment):

Event name: `ABCEventOccured`
DDL: `atomic.com_acme_abc_event_occured_1`
SQL filename: `abcevent_occured_1.sql`
JSONPaths filename: `abcevent_occured_1.json`

See incident [here](https://snowplow.zendesk.com/agent/tickets/5957) for more details.

**Comment by chuwy** [comment]
Hey @oguzhanunlu, could you please do some quick research for us?

Could you check if difference in this funcitons:

* https://github.com/snowplow/iglu/blob/master/0-common/schema-ddl/src/main/scala/com.snowplowanalytics/iglu.schemaddl/StringUtils.scala#L62-L66
* https://github.com/snowplow/snowplow-rdb-loader/blob/master/src/main/scala/com/snowplowanalytics/snowplow/rdbloader/utils/Common.scala

Can result in above inconsistency that Ihor mentioned? I'm quite keen to move this ticket to RDB Loader instead of Igluctl. Same for https://github.com/snowplow/iglu/issues/271

**Comment by chuwy** [comment]
I'm trying to remember why I didn't include Schema DDL as a dependency to use this function in RDB Loader. Probably I intentionally decided to make RDB Loader compatible with StorageLoader and now we have slightly inconsistent functions.

Anyway, single instance of this small, but super-important function must be used everywhere (maybe even include it to core?). Waiting for response from @oguzhanunlu.

**Comment by oguzhanunlu** [comment]
@chuwy Sorry for late response, didn't stop after doing quick research. I don't think diff between those functions is the problem (replacing dots with underscores). Looking at how sql and jsonpath filenames are generated to understand the issue.

**Comment by oguzhanunlu** [comment]
This is fixed through #271.
