### ISSUE TITLE
igluctl: overwrite old jsonpath files with `static generate` for minor version updates

### ISSUE THREAD

**Issue by colmsnowplow** [snowplow/iglu#346]
When I add fields to a schema in a minor version upgrade (1-0-0 to 1-0-1), then run `static generate` on it with `--with-json-paths`, a new file will be created in the `sql` folder to update the table, but the existing `jsonpaths` file won't be updated/overwritten unless I delete that file first.

Since not having a field in the `jsonpaths` file will cause a pipeline failure, I think Igluctl should detect minor version upgrades and overwrite the jsonpath file in these cases.

For non-technical users this is a difficult part of the tracking setup process, so I think we should make it as easy/foolproof as possible.

**Comment by chuwy** [comment]
Hey @colmsnowplow, thanks for report. For sure, JSONPaths file must always correspond to Redshift DDL. Correct behavior here would be following:

1. By default nothing should be overwritten. Notification should be printed if (and only if) there's a significant change in either JSONPaths or Redshift (only later can be checked)
2. If user provided `--force` flag - **both** JSONPath and Redshift DDL must be overwritten.

Did you provide `--force` flag? If not - then bug lays not in not-overwritten JSONPaths, but in overwritten DDL.

@oguzhanunlu, could you please check if igluctl conforms expected behavior?

**Comment by colmsnowplow** [comment]
Ah I see - no, I didn't use `--force` this issue looks to be user error then.

For the record it doesn't overwrite the DDL file in this case, it creates a new file (1-0-1), which contains `ALTER TABLE` statements to be run on the existing table.

I've just tested it, and `--force` does indeed overwrite the jsonpath file, along with the redshift DDLs. As long as we've followed the correct schemaVer convention for the schemas, this indeed produces the behaviour I'm after.

Thanks for the answer @chuwy!

**Comment by chuwy** [comment]
Thanks Colm, good to know. But did it print a warning that you can overwrite JSONPath using `--force` flag?

**Comment by colmsnowplow** [comment]
Nope, it simply overwrote the files, with the following  (abridged) output:

```
File [/Users/xxx/GitHub/com.example-schema-registry/./sql/com.example/event/1-0-0/1-0-3.sql] was overridden successfully (no change)!
```

**Comment by chuwy** [comment]
Ok, thanks. It means we still have some inconsistencies between desired and current behaviors. @oguzhanunlu, could you test assumptions and create a ticket to fix these inconsistencies.

**Comment by oguzhanunlu** [comment]
Sure @chuwy , I'll.

**Comment by aldemirenes** [comment]
Migrated to https://github.com/snowplow-incubator/igluctl/issues/24
