### ISSUE TITLE
Documentation of static repo format

### ISSUE THREAD

**Issue by reitzig** [snowplow/iglu#377]
I'm setting up a schema repo and while we are not going to use Iglu _now_, I'd like to remain compatible so we can switch if we need to without much hassle. To that end, I'd like to conform to Iglu's repo structure as closely as possible.

However, on [the page on static repositories](https://github.com/snowplow/iglu/wiki/Static-repo), no information about the expected folder structure and file names is given. I tried to infer the structure from the `iglu:` URL example(s) but for all I know, the structure on the webserver may be completely different.

Please document what Iglu-compatible repos have to conform to.

**Comment by chuwy** [comment]
Hey @reitzig, thanks for raising, I added an example into that wiki page. In short, you can use [Iglu Central](https://github.com/snowplow/iglu-central) as an example, where only `schemas/` directory is in use.

In future, if you have support requests, please direct them to our [forums](http://discourse.snowplowanalytics.com/) so that other community members can participate and find this information in future. Closing this.

**Comment by reitzig** [comment]
Thanks, will do!
