### ISSUE TITLE
Cannot load schema into Scala schema repo

### ISSUE THREAD

**Issue by yalisassoon** [snowplow/iglu#70]
I run the Scala static repo and run it as follows:

```
java \
-Dconfig.file=/path/to/application.conf \
-jar /path/to/iglu-server-0.1.0 com.snowplowanalytics.iglu.server.Boot
```

I then create the super API key as per the documentation, in PSQL. (Note that Postgres is running on the same box as the server repo):

```sql
insert into apikeys (uid, vendor_prefix, permission, createdat)
values ('63235577-b617-4a62-a0f0-df11ee3009a7', '.', 'super', current_timestamp);
```

I use it to  create a key for com.example_company, using cURL:

```
$ curl \
>   localhost:8080/api/auth/keygen \
>   -X POST \
>   -H "api_key: 63235577-b617-4a62-a0f0-df11ee3009a7" \
>   -d "vendor_prefix=com.example_company"
{
  "read" : "3e2b35e8-11eb-4954-b729-0c7f0e8d1220",
  "write" : "08cd8c22-800f-4f35-9b72-f8b7915c2fc6"
}
```

I then want to add an example schema, using the write key created above:

```
curl \
  localhost:8080/api/schemas/com.example_company/example_event/jsonschema/1-0-0 \
  -X POST \
  -H "api_key: 08cd8c22-800f-4f35-9b72-f8b7915c2fc6" \
  -d "{
  \"$schema\": \"http://iglucentral.com/schemas/com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0#\",
  \"description\": \"Schema for an example event\",
  \"self\": {
    \"vendor\": \"com.example_company\",
    \"name\": \"example_event\",
    \"format\": \"jsonschema\",
    \"version\": \"1-0-0\"
  },

  \"type\": \"object\",
  \"properties\": {
    \"exampleStringField\": {
      \"type\": \"string\",
      \"maxLength\": 255
    },
    \"exampleIntegerField\": {
      \"type\": \"integer\"
    },
    \"exampleNumericField\": {
      \"type\": \"number\",
      \"maxDecimal\": 3
    },
    \"exampleTimestampField\": {
      \"type\": \"string\",
      \"format\": \"date-time\"
    }
  },
  \"minProperties\":1,
  \"required\": [\"exampleStringField\", \"exampleIntegerField\"],
  \"additionalProperties\": false
}"
```

But get the following error message:

```
The requested resource could not be found.
```

**Comment by ashramsey** [comment]
Hey guys, any progress on this? I'm experiencing the 'Unrecognized token 'not'' error too.

**Comment by alexanderdean** [comment]
No progress yet

**Comment by BenFradet** [comment]
I'll try to have a look.

**Comment by ashramsey** [comment]
Cheers guys, I'm happy to look at trying out the static repo option in the meantime :-)

**Comment by alexanderdean** [comment]
Cheers @BenFradet, @ashramsey. In the meantime, yes the static repo works pretty well...

**Comment by fblundun** [comment]
In the second case (vendor name which doesn't contain an underscore) the problem seems to be this: when the schema is uploaded, the server attempts to validate it against the `com.snowplowanalytics.self-desc/schema/jsonschema/1-0-0` schema. But that schema doesn't exist in the database, so thequery attempting to get it returns the string "not found", which causes the error
`Unrecognized token 'not': was expecting 'null', 'true', 'false' or NaN`

**Comment by alexanderdean** [comment]
Ah! Good sleuthing. So that's a schema which is typically available in an embedded schema repo in an iglu client. I guess we need to "bootstrap" a new Iglu scala repo with all the schemas found in an embedded schema repo...

**Comment by fblundun** [comment]
If I manually insert the self-desc schema, everything seems to work as expected! Bootstrapping is the way to go.

When the vendor name does contain an underscore, the problem is down to the first regex in [this line](https://github.com/snowplow/iglu/blob/04815872ab7a919b0b0f4128e7b9b77ae82355ee/2-repositories/scala-repo-server/src/main/scala/com.snowplowanalytics.iglu.server/service/SchemaService.scala#L217), which doesn't allow underscores. There are several duplicates of these mistaken regexes in the repo. They should all be replaced with something based on https://github.com/snowplow/snowplow/issues/1998.

**Comment by alexanderdean** [comment]
That's encouraging!

**Comment by fblundun** [comment]
Splitting this into #80 and #81

**Comment by BenFradet** [comment]
Sorry I haven't been able to look into this, but have you looked into the unmerged stuff and particularly #65 and 3c66f0d .

**Comment by fblundun** [comment]
Thanks @BenFradet - I wasn't aware of that branch! Do you have any idea why the tests don't pass in either branch?

**Comment by BenFradet** [comment]
You mean all the tests?

**Comment by fblundun** [comment]
Some of them pass but others don't.

I'm getting:

```
[error] Error: Total 263, Failed 134, Errors 6, Passed 123
[error] Failed tests:
[error] 	com.snowplowanalytics.iglu.server.test.service.ApiKeyGenServiceSpec
[error] 	com.snowplowanalytics.iglu.server.test.service.SchemaServiceSpec
[error] 	com.snowplowanalytics.iglu.server.test.service.ValidationServiceSpec
[error] Error during tests:
[error] 	com.snowplowanalytics.iglu.server.test.actor.SchemaActorSpec
[error] 	com.snowplowanalytics.iglu.server.test.actor.ApiKeyActorSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 47 s, completed 11-Nov-2015 15:34:51
```

Most of the failures seem to be caused by an unexpected response of 401 Credentials Rejected.

**Comment by BenFradet** [comment]
Is this on master or feature?
Because it might be linked to #63 and 8cdc771.

**Comment by fblundun** [comment]
This is on both master and feature/scala-repo-server-0.2.0. (In both cases, after I have done #78 in that branch to get it compiling.) I notice that in feature/scala-repo-server-0.2.0, a super API key is created automatically because of the commit you linked. In master I created the super key myself.

**Comment by BenFradet** [comment]
Weird, all tests were passing when I stopped developing the project.
I think it has something to do with [this](https://github.com/snowplow/iglu/blob/master/2-repositories/scala-repo-server/src/main/scala/com.snowplowanalytics.iglu.server/util/TokenAuthenticator.scala#L74) since I give back a credentials rejected only there.

**Comment by fblundun** [comment]
I think I see part of the problem - some of the tests (like [this one](https://github.com/snowplow/iglu/blob/fad222fd901a8019fcc4eacba778d4c290fb30ac/2-repositories/scala-repo-server/src/test/scala/com.snowplowanalytics.iglu.server/service/SchemaServiceSpec.scala#L38-L42)) use API keys like 6eadba20-9b9f-4648-9c23-770272f8d627 which don't ever seem to be explicitly created.

**Comment by BenFradet** [comment]
I now remember that I used to do some manual initialization for my unit tests like adding some schemas and api keys as detailed [here](https://gist.github.com/BenFradet/bfd6069db4ac984afd95), sorry.

**Comment by fblundun** [comment]
That would explain it!

**Comment by fblundun** [comment]
@yalisassoon When you execute the command

```
```

**Comment by yalisassoon** [comment]
thanks @fblundun ! Great to know...
