### ISSUE TITLE
Repo Syncer: add

### ISSUE THREAD

**Issue by alexanderdean** [snowplow/iglu#77]
1. Fetch each schema from under /schemas (e.g. https://github.com/snowplow/iglu-central)
2. POST each schema to an Iglu Scala Repo

**Comment by fblundun** [comment]
I've got this working for iglucentral.com, but there's one problem: I can't seem to download every JSON, just the 13 linked to in [index.html](http://iglucentral.com/). This happens when I use

```bash
httrack iglucentral.com --robots=0
```

or

```bash
wget -r -l inf -e robots=off --no-cookies iglucentral.com
```

Any idea what about the website might be causing this?

It's not a huge problem since we can just download the latest Iglu Central release from GitHub instead.

**Comment by alexanderdean** [comment]
I think push from local copy is safest...
